### PR TITLE
[JENKINS-40683] Create functional tests for some provided tokens

### PR DESCRIPTION
**Pull request by varyvol**
[JENKINS-40683](https://issues.jenkins-ci.org/browse/JENKINS-40683)

Created functional tests for tokens:
- BUILD_NUMBER
- JENKINS_URL
- PROJECT_NAME
- PROJECT_URL

@reviewbybees

### CODE REVIEW

**Comment by slide** [comment]
There is already a test for JENKINS_URL

https://github.com/jenkinsci/token-macro-plugin/blob/master/src/test/java/org/jenkinsci/plugins/tokenmacro/TokenMacroTest.java#L36

**Comment by varyvol** [comment]
@slide I think BUILD_URL token does not use JENKINS_URL one in a nested way so, though strange, one could work properly meanwhile the other don't.

**Comment by slide** [comment]
Hah, it's what I get for looking after just waking up.

**Comment by varyvol** [comment]
@slide do you think it would be possible to release a new version including the latest changes?

**Pull request merged**
